filetype plugin on
filetype indent on
set background=dark
syntax on

" General configuration
set encoding=utf-8
set grepprg=grep\ -nH\ $*
set showmode number ruler   " Aesthetics (numbers around and mode we're in)
set nocompatible nomodeline " Use Vim defaults
set ts=4 sw=4 et ai         " Indents with 4 spaces
set history=50              " CLI history
set bs=indent,eol,start     " Backspace for lines and indentation
set ww=b,s,<,>,[,]          " Arrows & [back]space wordwraps between lines
set tw=79 nowrap            " PEP-8 line break without visual wordwrapping

" Whitespaces
set list lcs=tab:¤·,trail:· " Shows TABs and trailing chars
hi TABs ctermbg=Red ctermfg=LightRed guibg=Red guifg=LightRed term=italic
hi TrSp ctermbg=DarkGray ctermfg=Red guibg=DarkGray guifg=Red term=italic
call matchadd("TABs", "\t")      " All TABs but the trailing ones
call matchadd("TrSp", "\\s\\+$") " Trailing TABs and spaces

" Paste mouse selected text with Shift+Insert
if has('gui_running')
  map <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>
endif

